//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DBBOFCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int ProfileEmployeeID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> InactiveDatetime { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string GlobalEmployeeID { get; set; }
        public string EMail { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string GlobalProfileID { get; set; }
        public string PassportID { get; set; }
        public Nullable<int> LocalEmployeeID { get; set; }
        public Nullable<bool> RequestCard { get; set; }
        public Nullable<System.DateTime> DateRequestCard { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public string PrintedID { get; set; }
        public Nullable<int> OriginID { get; set; }
        public bool ManualUpdate { get; set; }
        public Nullable<System.DateTime> ManualTimeStamp { get; set; }
        public Nullable<int> ManualBOUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string ManualUpdateReason { get; set; }
        public Nullable<bool> HaveAffinity { get; set; }
        public Nullable<System.DateTime> StartDateAffinity { get; set; }
        public Nullable<bool> HaveTemporaryDiscount { get; set; }
        public Nullable<System.DateTime> StartDateTemporaryDiscount { get; set; }
        public Nullable<bool> AllowOwnMaxAmount { get; set; }
        public Nullable<int> OwnMaxAmount { get; set; }
        public Nullable<int> TypeLocationID { get; set; }
        public string EnumTypeEmployeeID { get; set; }
        public string CECO { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ProfileEmployee ProfileEmployee { get; set; }
    }
}
