//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DBBOFCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int EventoID { get; set; }
        public int TipoEventoID { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual TipoEvento TipoEvento { get; set; }
    }
}
