//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DBBOFCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroWidget_Grupo
    {
        public int ParametroWidgetGrupoID { get; set; }
        public int ParametroWidgetID { get; set; }
        public Nullable<int> GrupoID { get; set; }
        public string Valor { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual ParametroWidget ParametroWidget { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
