//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DBBOFCT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroWidget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParametroWidget()
        {
            this.ParametroWidget_Grupo = new HashSet<ParametroWidget_Grupo>();
        }
    
        public int ParametroWidgetID { get; set; }
        public string ValorDefecto { get; set; }
        public int WidgetID { get; set; }
        public int ParametroID { get; set; }
    
        public virtual Parametro Parametro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParametroWidget_Grupo> ParametroWidget_Grupo { get; set; }
    }
}
